version: "3.9"
services:
  jazzerspostgres:
    container_name: jazzers-postgres
    image: postgres:latest
    restart: always
    volumes:
      - jazzers_data:/var/jazzers_data
    environment:
      - PGDATA=/var/jazzers_data
      - POSTGRES_USER=${JAZZERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${JAZZERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=jazzersdb
    ports:
      - ${JAZZERS_POSTGRES_PORT}:${JAZZERS_POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${JAZZERS_POSTGRES_PORT}
    expose:
      - ${JAZZERS_POSTGRES_PORT}
  jazzersldap:
    container_name: jazzers-ldap
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - '10389:10389'
      - '10636:10636'
    command: [ "--copy-service" ]
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_BASE_DN: "dc=ad,dc=teamC,dc=net"
      LDAP_ORGANISATION: "Jazzers"
      LDAP_DOMAIN: "ad.teamC.net"
      LDAP_TLS: "false"
      LDAP_PORT: "10389"
    volumes:
      - ./src/main/resources/META-INF/employees-ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap-data.ldif
  jazzersserver:
    container_name: jazzers-server
    build: .
    ports:
      - ${JAZZERS_RMI_PORT}:${JAZZERS_RMI_PORT}
    links:
      - jazzerspostgres
    env_file:
      - .env
    command: -p ${JAZZERS_RMI_PORT}
    expose:
      - ${JAZZERS_RMI_PORT}
volumes:
  jazzers_data:


