version: "3.9"
services:
  jazzersactivemq:
    container_name: jazzers-activemq
    image: rmohr/activemq:latest
    restart: always
    ports:
      # jakarta messaging
      - "61616:61616"
      # web console
      - "8161:8161"
  jazzerspostgres:
    container_name: jazzers-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bZ+XdvLx45M=
      - POSTGRES_DB=jazzersdb
    ports:
      - "5434:5434"
    command: -p 5434
    expose:
      - 5434
  jazzersldap:
    container_name: jazzers-ldap
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - '10389:10389'
      - '10636:10636'
    command: [ "--copy-service" ]
    environment:
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_BASE_DN: "dc=ad,dc=teamC,dc=net"
      LDAP_ORGANISATION: "Jazzers"
      LDAP_DOMAIN: "ad.teamC.net"
      LDAP_TLS: "false"
      LDAP_PORT: "10389"
    volumes:
      - ./employees-for-ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap-data.ldif
  jazzerswildfly:
    container_name: jazzers-wildfly
    build: .
    depends_on:
      - jazzersactivemq
      - jazzerspostgres
      - jazzersldap
    ports:
      - "9990:9990"
      - "8080:8080"
    env_file:
      - .env