version: "3.9"
services:
  jazzerspostgres:
    container_name: jazzers-postgres
    image: postgres:latest
    restart: always
    volumes:
      - jazzers_data:/var/jazzers_data
    environment:
      - PGDATA=/var/jazzers_data
      - POSTGRES_USER=${JAZZERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${JAZZERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=jazzersdb
    ports:
      - ${JAZZERS_POSTGRES_PORT}:${JAZZERS_POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${JAZZERS_POSTGRES_PORT}
    expose:
      - ${JAZZERS_POSTGRES_PORT}
  jazzersserver:
    container_name: jazzers-server
    build: .
    ports:
      - ${JAZZERS_RMI_PORT}:${JAZZERS_RMI_PORT}
    links:
      - jazzerspostgres
    env_file:
      - .env
    command: -p ${JAZZERS_RMI_PORT}
    expose:
      - ${JAZZERS_RMI_PORT}
volumes:
  jazzers_data:


